# frozen_string_literal: true

module ApplicationCable
  # This class was generated by Rails as the base class for all ActionCable::Connections
  class Connection < ActionCable::Connection::Base
  end
end
